
ServerPort = 1324

[Postgres]
Host = "localhost"
Port = 5432
User = "superuser"
Password = "superuser"
DBName = "mydb"

[Rabbit]
RabbitURL = "localhost:5672"
RabbitUser = "guest:guest"
# RabbitUser = "krokodil:schnappi"
